### ISSUE TITLE
Memory leak - writer_queue in GrowingSpscQueue

### ISSUE THREAD

**Issue by dorav** [danikv/DanielThreadSafeLibrary#5]
The writer pointer may leak memory.

This is not easily fixable as if that memory was to be deleted, it might be deleted while the reading thread was inside syncReader, which could lead to data races.

Furthermore - One could suggest that the deletion will be done in the reading thread - but the reader might not read the data for a very long time, leading again to a mem-leak.

**Comment by danikv** [comment]
fixed
